# Common library doesn't need a Dockerfile as it's a dependency for other services
# This file is just a placeholder to indicate that this module doesn't need containerization
# The library will be built and included in the other service containers