server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/auth/**, /api/roles/**, /api/permissions/**, /api/groups/**
          filters:
            - name: JwtAuthenticationFilter
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: JwtAuthenticationFilter

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentEnvironmentOnly}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:2592000000}